# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(740, 20, 51, 31))
        self.load.setObjectName("load")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(690, 430, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.learn = QtWidgets.QLineEdit(self.centralwidget)
        self.learn.setGeometry(QtCore.QRect(560, 430, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.learn.setFont(font)
        self.learn.setObjectName("learn")
        self.condition = QtWidgets.QLineEdit(self.centralwidget)
        self.condition.setGeometry(QtCore.QRect(560, 500, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.condition.setFont(font)
        self.condition.setObjectName("condition")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(430, 440, 91, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(430, 500, 91, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setDragEnabled(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 500, 121, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setDragEnabled(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 440, 121, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(16)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setDragEnabled(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setClearButtonEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.menu = QtWidgets.QComboBox(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(557, 20, 171, 31))
        self.menu.setMaxCount(2147483644)
        self.menu.setObjectName("menu")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.menu.addItem("")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 491, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ltest = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ltest.setContentsMargins(0, 0, 0, 0)
        self.ltest.setObjectName("ltest")
        self.clear_layout = QtWidgets.QPushButton(self.centralwidget)
        self.clear_layout.setGeometry(QtCore.QRect(690, 500, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.clear_layout.setFont(font)
        self.clear_layout.setObjectName("clear_layout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 440, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 500, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(550, 240, 241, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.test = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.test.setContentsMargins(0, 0, 0, 0)
        self.test.setObjectName("test")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(550, 70, 241, 161))
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load.setText(_translate("MainWindow", "load"))
        self.start.setText(_translate("MainWindow", "start"))
        self.lineEdit.setText(_translate("MainWindow", "學習率"))
        self.lineEdit_2.setText(_translate("MainWindow", "收斂條件"))
        self.lineEdit_4.setText(_translate("MainWindow", "測試辨識率"))
        self.lineEdit_5.setText(_translate("MainWindow", "訓練辨識率"))
        self.menu.setItemText(0, _translate("MainWindow", "perceptron1.txt"))
        self.menu.setItemText(1, _translate("MainWindow", "2Ccircle1.txt"))
        self.menu.setItemText(2, _translate("MainWindow", "2Circle1.txt"))
        self.menu.setItemText(3, _translate("MainWindow", "2Circle2.txt"))
        self.menu.setItemText(4, _translate("MainWindow", "2CloseS.txt"))
        self.menu.setItemText(5, _translate("MainWindow", "2CloseS2.txt"))
        self.menu.setItemText(6, _translate("MainWindow", "2CloseS3.txt"))
        self.menu.setItemText(7, _translate("MainWindow", "2cring.txt"))
        self.menu.setItemText(8, _translate("MainWindow", "2CS.txt"))
        self.menu.setItemText(9, _translate("MainWindow", "2Hcircle1.txt"))
        self.menu.setItemText(10, _translate("MainWindow", "2ring.txt"))
        self.menu.setItemText(11, _translate("MainWindow", "perceptron2.txt"))
        self.clear_layout.setText(_translate("MainWindow", "clear"))

